<?php return array(
    'root' => array(
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '24d058fe3efa69df62227b37e9e1864ef574f609',
        'name' => 'stake2/ecommerce',
        'dev' => true,
    ),
    'versions' => array(
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.5.3',
            'version' => '6.5.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'reference' => 'baeb7cde6b60b1286912690ab0693c7789a31e71',
            'dev_requirement' => false,
        ),
        'rain/raintpl' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../rain/raintpl',
            'aliases' => array(),
            'reference' => '5bfdf4602b8adb0e80b222fa29ac559aa9c06abf',
            'dev_requirement' => false,
        ),
        'slim/slim' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../slim/slim',
            'aliases' => array(),
            'reference' => '3e95c9abbc57a8f023ab4dacebcab9dae4d9f1f0',
            'dev_requirement' => false,
        ),
        'stake2/ecommerce' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '24d058fe3efa69df62227b37e9e1864ef574f609',
            'dev_requirement' => false,
        ),
    ),
);
